console.log("js conectado");
const tempData = [
  {
    title: "El Señor de los Anillos: La Comunidad del Anillo",
    year: "2001",
    director: "Peter Jackson",
    duration: "178 min",
    genre: "Aventura, Fantasía",
    rate: "8.8",
    poster: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
  },
  {
    title: "The Matrix",
    year: "1999",
    director: "Lana Wachowski, Lilly Wachowski",
    duration: "136 min",
    genre: "Acción, Ciencia Ficción",
    rate: "8.7",
    poster:
      "https://image.tmdb.org/t/p/w600_and_h900_bestv2/vJ5BqyKKya7KFQYSgqZHEKhE8zU.jpg",
  },
  {
    title: "It",
    year: "2017",
    director: "Andy Muschietti",
    duration: "135 min",
    genre: "Terror, Drama",
    rate: "7.3",
    poster: "https://image.tmdb.org/t/p/w500/9E2y5Q7WlCVNEhP5GiVTjhEhx1o.jpg",
  },
  {
    title: "Gladiator",
    year: "2000",
    director: "Ridley Scott",
    duration: "155 min",
    genre: "Acción, Aventura, Drama",
    rate: "8.5",
    poster: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
  },
  {
    title: "Whiplash",
    year: "2014",
    director: "Damien Chazelle",
    duration: "106 min",
    genre: "Drama, Música",
    rate: "8.5",
    poster:
      "https://image.tmdb.org/t/p/w600_and_h900_bestv2/sL32IZkyjlF7otj5vcUxiKSKzg5.jpg",
  },
  {
    title: "El niño con el pijama de rayas",
    year: "2008",
    director: "Mark Herman",
    duration: "94 min",
    genre: "Drama, Guerra",
    rate: "7.8",
    poster:
      "https://image.tmdb.org/t/p/w600_and_h900_bestv2/dZeiD0WVM1IHzRAOSldsY0jh1CR.jpg",
  },
  {
    title: "Taxi Driver",
    year: "1976",
    director: "Martin Scorsese",
    duration: "114 min",
    genre: "Crimen, Drama",
    rate: "8.2",
    poster: "https://image.tmdb.org/t/p/w500/ekstpH614fwDX8DUln1a2Opz0N8.jpg",
  },
  {
    title: "Blade Runner 2049",
    year: "2017",
    director: "Denis Villeneuve",
    duration: "164 min",
    genre: "Acción, Drama, Misterio",
    rate: "8.0",
    poster: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
  },
  {
    title: "Drive",
    year: "2011",
    director: "Nicolas Winding Refn",
    duration: "100 min",
    genre: "Crimen, Drama",
    rate: "7.8",
    poster:
      "https://image.tmdb.org/t/p/w600_and_h900_bestv2/uC6ykM4OcOaxS7mLMdF7eebdk1Z.jpg",
  },
  {
    title: "Oppenheimer",
    year: "2023",
    director: "Christopher Nolan",
    duration: "180 min",
    genre: "Biografía, Drama, Historia",
    rate: "8.5",
    poster:
      "https://image.tmdb.org/t/p/w600_and_h900_bestv2/ncKCQVXgk4BcQV6XbvesgZ2zLvZ.jpg",
  },
];
